CREATE TABLE IF NOT EXISTS USERS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  CURRENCY VARCHAR(4) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  NAME VARCHAR(255),
  TYPE VARCHAR(255),
  PRIMARY KEY(ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS ASSETS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CODE VARCHAR(255),
  TYPE VARCHAR(255),
  TAX_RULE VARCHAR(255),
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  NAME VARCHAR(255),
  PARENT BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY(PARENT) REFERENCES CATEGORIES(ID)
);

CREATE TABLE IF NOT EXISTS CREDIT_CARDS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  NAME VARCHAR(255),
  ICON VARCHAR(255),
  CLOSING_DAY_OF_MONTH INT,
  PAYMENT_DAY_OF_MONTH INT,
  PRIMARY KEY (ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS CREDIT_CARD_STATEMENTS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  CARD_ID BIGINT NOT NULL,
  CLOSING_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY(CARD_ID) REFERENCES CREDIT_CARDS(ID)
);

CREATE TABLE IF NOT EXISTS GOALS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  NAME VARCHAR(255),
  TYPE VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GOAL_MARKS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  GOAL_ID BIGINT NOT NULL,
  REALIZATION_DATETIME TIMESTAMP NOT NULL,
  VALUE FLOAT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(GOAL_ID) REFERENCES GOALS(ID)
);

CREATE TABLE IF NOT EXISTS MARKET_DATA (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ASSET_ID BIGINT NOT NULL,
  QUOTATION_DATETIME TIMESTAMP NOT NULL,
  CLOSE_VALUE FLOAT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY(ASSET_ID) REFERENCES ASSETS(ID)
);

CREATE TABLE IF NOT EXISTS POSITIONS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  ASSET_ID BIGINT NOT NULL,
  QUANTITY BIGINT,
  PURCHASE_VALUE FLOAT,
  ACCOUNT_ID BIGINT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY(ASSET_ID) REFERENCES ASSETS(ID),
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS_HEADER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL,
  TITLE VARCHAR(255),
  CATEGORY_ID BIGINT,
  TRANSACTION_DATE DATETIME,
  PAYMENT_DATE DATETIME,
  CREATION_DATE DATETIME,
  LAST_MODIFIED_DATE DATETIME,
  PRIMARY KEY(ID),
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTION_ITEMS (
  HEADER_ID BIGINT NOT NULL,
  ITEM_SEQUENCE BIGINT NOT NULL,
  IS_INVISIBLE BOOLEAN,
  IS_ACCOUNTABLE BOOLEAN,
  ACCOUNT_ID BIGINT,
  POSITION_ID BIGINT,
  CREDIT_CARD_STATEMENT_ID BIGINT,
  VALUE FLOAT,
  PRIMARY KEY(HEADER_ID, ITEM_SEQUENCE),
  FOREIGN KEY(HEADER_ID) REFERENCES TRANSACTIONS_HEADER(ID),
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
  FOREIGN KEY(CREDIT_CARD_STATEMENT_ID) REFERENCES CREDIT_CARD_STATEMENTS(ID),
  FOREIGN KEY(POSITION_ID) REFERENCES POSITIONS(ID)
);